import tkinter as tk
from datetime import datetime
from database.queries import save_bill
from dashboard.profile import open_profile
from dashboard.calculator import button_click,calculate,clear
from billing.bill_generator import add_item,exit_app
from billing.bill_generator import generate_bill,clear_bill,calculate_total
from tkinter import ttk, messagebox
from billing.bill_history import open_bill_history
from database.queries import get_next_bill_no
def open_dashboard():
    window = tk.Tk()
    window.title("RESTAURANT MANAGMENT SYSTEM")
    window.state("zoomed")
    window.geometry("1300x750")
    title_frame = tk.Frame(window, bg="#C0C0C0", width=1500, height=55, bd=2, relief="groove")
    title_frame.pack(pady=15, padx=20, fill="x")
    title_frame.pack_propagate(False)
    name = tk.Label(title_frame, text="RESTAURANT MANAGEMENT SYSTEM", font=("Times New Roman", 25, "bold"), fg="black",bg="#C0C0C0")
    name.pack(side="top", pady=10)
    history_btn = tk.Button(title_frame, text="Bill History", font=("Arial", 10, "bold"), width=10,command=open_bill_history)
    history_btn.place(relx=0.01, rely=0.5, anchor="w")
    profile_btn = tk.Button(title_frame, text="Profile", font=("Arial", 10, "bold"), width=8,command= lambda :open_profile(window))
    profile_btn.place(relx=0.99, rely=0.5, anchor="e")
    details_frame = tk.Frame(window, bg="#C0C0C0", width=650, height=690, bd=2, relief="groove")
    details_frame.pack(padx=57, pady=1, anchor="w")
    details_frame.propagate(False)
    enterdetails_frame = tk.Frame(details_frame, bg="#D3D3D3", width=620, height=35, bd=1, relief="groove")
    enterdetails_frame.pack_propagate(False)
    enterdetails_frame.pack(fill="x", padx=5, pady=3)
    enter_details = tk.Label(enterdetails_frame, text="Enter Details", font=("Arial", 16, "bold"), fg="black",bg="#D3D3D3")
    enter_details.pack(pady=5)
    costomer_frame = tk.Frame(details_frame, bg="#D3D3D3", width=620, height=415, bd=2, relief="groove")
    costomer_frame.pack(fill="x", padx=5, pady=3)
    costomer_frame.pack_propagate(False)
    bill = tk.Label(costomer_frame, text="○ Bill Number :", font=("Arial", 14, "bold"), fg="black", bg="#D3D3D3")
    bill.grid(row=0, column=0, padx=(15, 10), pady=7, sticky="w")
    bill_entry = tk.Entry(costomer_frame, font=("Arial", 12), width=40)
    bill_no = get_next_bill_no()
    bill_entry.insert(0,str(bill_no))
    bill_entry.config(state="readonly")
    bill_entry.grid(row=0, column=1, padx=10, pady=7, sticky="w")
    name = tk.Label(costomer_frame, text="○ Costomer Name :", font=("Arial", 14, "bold"), fg="black", bg="#D3D3D3")
    name.grid(row=1, column=0, padx=(15, 10), pady=7, sticky="w")
    name_entry = tk.Entry(costomer_frame, font=("Arial", 12), width=40)
    name_entry.grid(row=1, column=1, padx=10, pady=7, sticky="w")
    contact = tk.Label(costomer_frame, text=" ○ Costomer Contact :", font=("Arial", 14, "bold"), fg="black",bg="#D3D3D3")
    contact.grid(row=2, column=0, padx=10, pady=7, sticky="w")
    contact_entry = tk.Entry(costomer_frame, font=("Arial", 12,), width=40)
    contact_entry.grid(row=2, column=1, padx=10, pady=7, sticky="w")
    city = tk.Label(costomer_frame, text=" ○ City :", font=("Arial", 14, "bold"), fg="black", bg="#D3D3D3")
    city.grid(row=3, column=0, padx=10, pady=7, sticky="w")
    city_entry = tk.Entry(costomer_frame, font=("Arial", 12), width=40)
    city_entry.grid(row=3, column=1, padx=10, pady=7, sticky="w")
    date = tk.Label(costomer_frame, text=" ○ Date :", font=("Arial", 14, "bold"), fg="black", bg="#D3D3D3")
    date.grid(row=4, column=0, padx=10, pady=7, sticky="w")
    date_entry = tk.Entry(costomer_frame, font=("Arial", 12), width=40)
    date_entry.grid(row=4, column=1, padx=10, pady=7, sticky="w")
    time = tk.Label(costomer_frame, text=" ○ Time :", font=("Arial", 14, "bold"), fg="black", bg="#D3D3D3")
    time.grid(row=5, column=0, padx=10, pady=7, sticky="w")
    time_entry = tk.Entry(costomer_frame, font=("Arial", 12), width=40)
    time_entry.grid(row=5, column=1, padx=10, pady=7, sticky="w")
    current_date = datetime.now().strftime("  %d-%m-%Y")
    current_time = datetime.now().strftime("  %I:%M %p")
    date_entry.insert(0, current_date)
    time_entry.insert(0, current_time)
    date_entry.config(state="readonly")
    time_entry.config(state="readonly")
    item_purchase = tk.Label(costomer_frame, text=" ○ Items Purchased :", font=("Arial", 14, "bold"), fg="black",bg="#D3D3D3")
    item_purchase.grid(row=6, column=0, padx=10, pady=7, sticky="w")
    purchase_entry = tk.Entry(costomer_frame, font=("Arial", 12), width=40)
    purchase_entry.grid(row=6, column=1, padx=10, pady=7, sticky="w")
    quantity = tk.Label(costomer_frame, text=" ○ Item Quantity :", font=("Arial", 14, "bold"), fg="black", bg="#D3D3D3")
    quantity.grid(row=7, column=0, padx=10, pady=7, sticky="w")
    quantity_dropdown = ttk.Combobox(costomer_frame, font=("Arial", 12), width=38, state="readonly")
    quantity_dropdown["values"] = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
    quantity_dropdown.grid(row=7, column=1, padx=10, pady=7, sticky="w")
    quantity_dropdown.current(0)
    cost = tk.Label(costomer_frame, text=" ○ Cost of One", font=("Arial", 14, "bold"), fg="black", bg="#D3D3D3")
    cost.grid(row=8, column=0, padx=10, pady=7, sticky="w")
    cost_dropdown = ttk.Combobox(costomer_frame, font=("Arial", 12), width=38, state="readonly")
    cost_dropdown["values"] = (10, 15, 20, 25, 30, 40, 50, 75, 100, 110, 125, 150, 175, 200, 250, 300, 350, 400, 450,500)
    cost_dropdown.current(0)
    cost_dropdown.grid(row=8, column=1, padx=10, pady=7, sticky="w")
    table_no = tk.Label(costomer_frame, text=" ○ Table No :", font=("", 14, "bold"), fg="black", bg="#D3D3D3")
    table_no.grid(row=9, column=0, padx=10, pady=7, sticky="w")
    table_dropdown = ttk.Combobox(costomer_frame, font=("Arial", 12), width=38, state="readonly")
    table_dropdown["values"] = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
    table_dropdown.current(0)
    table_dropdown.grid(row=9, column=1, padx=10, pady=7, sticky="w")
    # Calculator
    calculator_frame = tk.Frame(window, bg="#C0C0C0", width=725, height=400, bd=2, relief="groove")
    calculator_frame.place(x=750, y=88)
    calculator_frame.pack_propagate(False)
    calculator_title = tk.Label(calculator_frame, text="Calculator", font=("Arial", 18, "bold"), bg="#C0C0C0")
    calculator_title.pack(pady=2)
    calculator_entry = tk.Entry(calculator_frame, font=("Arial", 18), bg="white", justify="right", width=51)
    calculator_entry.pack(pady=2, ipady=15)
    # calculator button
    calbtn_frame = tk.Frame(calculator_frame, bg="#D3D3D3", bd=2, relief="groove")
    calbtn_frame.pack(pady=10)
    btn7 = tk.Button(calbtn_frame, text="7", font=("Arial", 20, "bold"), width=8, height=1,command=lambda : button_click(7,calculator_entry))
    btn7.grid(row=0, column=0, padx=10, pady=(8, 4))
    btn8 = tk.Button(calbtn_frame, text="8", font=("Arial", 20, "bold"), width=8, height=1,command=lambda : button_click(8,calculator_entry))
    btn8.grid(row=0, column=1, padx=10, pady=(8, 4))
    btn9 = tk.Button(calbtn_frame, text="9", font=("Arial", 20, "bold"), width=8, height=1,command=lambda : button_click(9,calculator_entry))
    btn9.grid(row=0, column=2, padx=10, pady=(8, 4))
    plus_btn = tk.Button(calbtn_frame, text="+", font=("Arial", 20, "bold"), width=8, height=1,command=lambda : button_click("+",calculator_entry))
    plus_btn.grid(row=0, column=3, padx=10, pady=(8, 4))
    btn4 = tk.Button(calbtn_frame, text="4", font=("Arial", 20, "bold"), width=8, height=1,command= lambda : button_click(4,calculator_entry))
    btn4.grid(row=1, column=0, padx=10, pady=4)
    btn5 = tk.Button(calbtn_frame, text="5", font=("Arial", 20, "bold"), width=8, height=1,command=lambda : button_click(5,calculator_entry))
    btn5.grid(row=1, column=1, padx=10, pady=4)
    btn6 = tk.Button(calbtn_frame, text="6", font=("Arial", 20, "bold"), width=8, height=1,command = lambda : button_click(6,calculator_entry))
    btn6.grid(row=1, column=2, padx=10, pady=4)
    minus_btn = tk.Button(calbtn_frame, text="−", font=("Arial", 20, "bold"), width=8, height=1,command=lambda : button_click("-",calculator_entry))
    minus_btn.grid(row=1, column=3, padx=10, pady=4)
    btn1 = tk.Button(calbtn_frame, text="1", font=("Arial", 20, "bold"), width=8, height=1,command=lambda : button_click(1,calculator_entry))
    btn1.grid(row=2, column=0, padx=10, pady=4)
    btn2 = tk.Button(calbtn_frame, text="2", font=("Arial", 20, "bold"), width=8, height=1,command=lambda : button_click(2,calculator_entry))
    btn2.grid(row=2, column=1, padx=10, pady=4)
    btn3 = tk.Button(calbtn_frame, text="3", font=("Arial", 20, "bold"), width=8, height=1,command=lambda : button_click(3,calculator_entry))
    btn3.grid(row=2, column=2, padx=10, pady=4)
    mul_btn = tk.Button(calbtn_frame, text="×", font=("Arial", 20, "bold"), width=8, height=1,command=lambda : button_click("*",calculator_entry))
    mul_btn.grid(row=2, column=3, padx=10, pady=4)
    clr_btn = tk.Button(calbtn_frame, text="⌫", font=("Arial", 20, "bold"), width=8, height=1,command=lambda: clear(calculator_entry))
    clr_btn.grid(row=3, column=0, padx=10, pady=8)
    zero_btn = tk.Button(calbtn_frame, text="0", font=("Arial", 20, "bold"), width=8, height=1,command=lambda : button_click(0,calculator_entry))
    zero_btn.grid(row=3, column=1, padx=10, pady=8)
    equal_btn = tk.Button(calbtn_frame, text="=", font=("Arial", 20, "bold"), width=8, height=1,command=lambda : calculate(calculator_entry))
    equal_btn.grid(row=3, column=2, padx=10, pady=8)
    div_btn = tk.Button(calbtn_frame, text="÷", font=("Arial", 20, "bold"), width=8, height=1,command=lambda : button_click("/",calculator_entry))
    div_btn.grid(row=3, column=3, padx=10, pady=8)
    # Bill Area
    bill_frame = tk.Frame(window, bg="#D3D3D3", bd=2, relief="groove", height=273, width=725)
    bill_frame.place(x=750, y=500)
    bill_frame.pack_propagate(False)
    bill_title = tk.Label(bill_frame, text="Billing Area", font=("Arial", 14, "italic"), bg="#D3D3D3")
    bill_title.pack(pady=1)
    # scrollbar
    scrollbar = tk.Scrollbar(bill_frame)
    scrollbar.pack(side="right", fill="y")
    bill_text = tk.Text(bill_frame, font=("Courier New", 11), bg="white")
    bill_text.pack(side="left", fill="both", expand=True, padx=8)
    bill_text.config(state="normal")
    bill_text.insert("end", "\n", "title")
    bill_text.tag_config("title", font=("Courier New", 13, "bold"), justify="center")  # Title Style
    bill_text.tag_config("address", font=("Courier New", 12))  # Address Style
    bill_text.tag_config("total", font=("Courier New", 12, "bold"))  # Total Style
    bill_text.insert("end", "\n", "title")
    bill_text.insert("end", "Shivshahi Family Restaurant & Bar \n", "title")
    bill_text.insert("end", "               Ring road, Amravati, Maharashtra 444605\n", "address")
    bill_text.insert("end", "        ------------------------------------------------------------\n\n")
    bill_text.config(state="disabled")
    #Function for save button
    def save_bill_data():
        costomer_name = name_entry.get()
        contact = contact_entry.get()
        city = city_entry.get()
        bill_date = date_entry.get()
        bill_time = time_entry.get()
        table_no = table_dropdown.get()
        grand_total = calculate_total(bill_text)
        save_bill(costomer_name,contact,city,bill_date,bill_time,table_no,grand_total)
        messagebox.showinfo("Success", "Bill Saved Successfully")
        new_bill_no = get_next_bill_no()
        bill_entry.config(state="normal")
        bill_entry.delete(0, "end")
        bill_entry.insert(0,str(new_bill_no))
        bill_entry.config(state="readonly")
    # button
    button_frame = tk.Frame(details_frame, bg="#C0C0C0", width=620, height=205, bd=2, relief="groove")
    button_frame.pack(fill="x", padx=20, pady=15)
    add_btn = tk.Button(button_frame, text="Add", font=("Arial", 20, "bold"), bg="white", fg="black", width=7, height=1,bd=1, relief="solid",command=lambda : add_item(purchase_entry, quantity_dropdown, cost_dropdown, bill_text,))
    add_btn.grid(row=0, column=0, padx=20, pady=15)
    clear_btn = tk.Button(button_frame, text="Clear", font=("Arial", 20, "bold"), bg="white", fg="black", width=7,height=1, bd=1, relief="solid",command=lambda :clear_bill(name_entry,contact_entry,city_entry,purchase_entry, quantity_dropdown,cost_dropdown,table_dropdown,bill_text))
    clear_btn.grid(row=0, column=2, padx=20, pady=15)
    generate_btn = tk.Button(button_frame, text="Generate Bill", font=("Arial", 20, "bold"), bg="white", fg="black",width=13, height=1, bd=1, relief="solid",command=lambda : generate_bill(bill_entry, name_entry, contact_entry, city_entry,date_entry, time_entry, table_dropdown, bill_text))
    generate_btn.grid(row=0, column=1, padx=20, pady=15)
    total_btn = tk.Button(button_frame, text="Total", font=("Arial", 20, "bold"), bg="white", fg="black", width=7,height=1, bd=1, relief="solid", command=lambda : calculate_total(bill_text))
    total_btn.grid(row=1, column=0, padx=20, pady=15)
    save_btn = tk.Button(button_frame, text="Save Bill", font=("Arial", 20, "bold"), bg="white", fg="black", width=13,height=1, bd=1, relief="solid",command=save_bill_data)
    save_btn.grid(row=1, column=1, padx=20, pady=15)
    exit_btn = tk.Button(button_frame, text="Exit", font=("Arial", 20, "bold"), bg="white", fg="black", width=7,height=1, bd=1, relief="solid",command=lambda : exit_app(window))
    exit_btn.grid(row=1, column=2, padx=20, pady=15)


    window.mainloop()


